wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/tools/train_ppo.py
    python_version: 3.7.16
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682448518.661918
    t:
      1:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      3:
      - 23
      - 35
      4: 3.7.16
      5: 0.15.0
      8:
      - 5
